name: Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - run: dotnet build --configuration Release SingleFinite.Mvvm.WinUI
      - name: Create the package
        run: dotnet pack --configuration Release SingleFinite.Mvvm.WinUI
      - name: Publish the package
        run: dotnet nuget push SingleFinite.Mvvm.WinUI/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_TOKEN}}
